display:
  action_bubble_bg_color: null
  action_bubble_text_color: null
  agent_avatar_position: Middle
  agent_avatar_show: In Group
  assistant_bubble_bg_color: '#29282b'
  assistant_bubble_text_color: '#b2bbcf'
  code_bubble_bg_color: '#252427'
  code_bubble_text_color: '#999999'
  primary_color: '#151515'
  secondary_color: '#323232'
  text_color: '#c4c4c4'
  text_font: ''
  text_size: 14
  user_bubble_bg_color: '#3b3b3b'
  user_bubble_text_color: '#d1d1d1'
system:
  auto_title_model: perplexity/mistral-7b-instruct
  auto_title_prompt: Generate a brief and concise title for a chat that begins with
    the following message:\n\n{user_msg}
  debug: false
  dev_mode: 2
  passive_listen_secs: 300
  verbose: true
voice:
  mute_voice: false
