display:
  action_bubble_bg_color: null
  action_bubble_text_color: null
  assistant_bubble_bg_color: '#29282b'
  assistant_bubble_text_color: '#b2bbcf'
  code_bubble_bg_color: '#252427'
  code_bubble_text_color: '#999999'
  primary_color: '#1f1e21'
  secondary_color: '#3b3b3b'
  text_color: '#c4c4c4'
  text_font: ''
  text_size: 18
  user_bubble_bg_color: '#3b3b3b'
  user_bubble_text_color: '#d1d1d1'
system:
  db_path: ../data.db
  debug: true
  passive_listen_secs: 300
  termcolor_assistant: cyan
  termcolor_verbose: light_grey
  verbose: true
voice:
  mute_voice: false
