[tool.poetry]
name = "agentpilot"
version = "0.3.0"
description = "Universal GUI for seamless interaction and management of AI workflows"
authors = ["jbexta <agentpilotai@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.11"
PySide6 = "6.2.4"
#litellm = "^1.41.3"
mistune = "^3.0.2"
nest-asyncio = "^1.6.0"
open-interpreter = "^0.3.3"
matrix-nio = "^0.24.0"
langchain-community = "^0.2.5"
#langchain-openai = "^0.1.13"
langchain = "^0.2.5"
posthog = "^3.5.0"
cryptography = "^42.0.8"
#embedchain = "^0.1.114"
#instructor = "^1.3.4"
#crewai-tools = "^0.0.16"
opentelemetry-api = "^1.25.0"
opentelemetry-sdk = "^1.25.0"
opentelemetry-exporter-otlp-proto-http = "^1.25.0"
jsonref = "^1.1.0"
appdirs = "^1.4.4"
readchar = "^4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
