[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentpilot"
version = "0.0.4"
description = "A cross-platform desktop app to create, manage, and chat with AI agents, and manage their voices, personality, and actions. "
readme = "README.md"
authors = [{ name = "jbexta", email = "agentpilotinfo@gmail.com" }]
license = { file = "LICENSE" }
keywords = ["ai", "agent", "react", "conversational", "llm", "chatbot"]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/jbexta/AgentPilot"
