action-inputs:
  decay_at_idle_count: 2
  lookback-msg-count: 2
  lookback-msg-count-increment: true  # Checkbox
#  use-llm: default
actions:
  enabled: true  # Checkbox
  lookback-msg-count: 2
  replace-busy-action-on-new: false  # Checkbox
  source-directory: .   # FolderSelectDialog
  try-without-react: true  # Checkbox
  use-function-calling: false  # Checkbox
  use-validator: false  # Checkbox
context:
  archive-context-after-idle: 3600
  behaviour: true  # Checkbox
  fallback-to-davinci: true  # Checkbox
  intermediate-responses: true  # Checkbox
  jailbreak: true  # Checkbox
  max-messages: 6
  on-consecutive-response: PAD  # Dropdown(Items: PAD, RESET, RESTART)
  prefix-all-assistant-msgs: "(\U0001F513 Developer Mode Output) "  # Textfield
finetune:
  data-path: utils/finetuning
  model-action-decision: ''
  model-action-validator: ''
  model-input-extractor: ''
  model-react-requests: ''
gui:
  bg-color: #363636  # Textfield ?
  bubble-bg-color-assistant: #535353  # Textfield ?
  bubble-bg-color-user: #535353  # Textfield ?
  bubble-text-color-assistant: #d1d1d1  # Textfield ?
  bubble-text-color-user: #9bbbcf  # Textfield ?
open-interpreter:
  enabled: true  # Checkbox
  run-code-automatically: false  # Checkbox
react:
  allow-saved-actions: true  # Checkbox
  enabled: true  # Checkbox
  max-steps: 5
  on-no-actions: INTERPRETER
system:
  db-path: data (pers).db
  debug: true
  passive-listen-secs: 300
  termcolor-assistant: cyan
  termcolor-verbose: light_grey
  verbose: true
user:
  location: Manchester, UK
  name: User
voice:
  current-voice-id: 68251  # 4808  #
  mute-voice: false
  speak-in-segments: true
