display:
  bg_color: null
  bubble_bg_color_assistant: null
  bubble_bg_color_user: null
  bubble_text_color_assistant: null
  bubble_text_color_user: null
system:
  db_path: data.db
  debug: true
  passive_listen_secs: 300
  termcolor_assistant: cyan
  termcolor_verbose: light_grey
  verbose: true
voice:
  mute_voice: false
